### ISSUE TITLE
Fix synchronization issue

### ISSUE THREAD

**Issue by Chicoryn** [Chicoryn/dream-go#20]
Fix the following crash experienced twice when extracting features from 250,000 games (so pretty rare):

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: dream_go::mcts::predict::PredictState::predict
  11: <dream_go::mcts::predict::PredictState as dream_go::parallel::service::ServiceImpl>::process
  12: dream_go::parallel::service::worker_thread
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: <F as alloc::boxed::FnBox<A>>::call_box
  16: std::sys_common::thread::start_thread
             at /checkout/src/liballoc/boxed.rs:827
             at libstd/sys_common/thread.rs:24
  17: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  18: start_thread
  19: clone
```

**Comment by Chicoryn** [comment]
There is no `Option` in the `predict` function itself or its control flow as far as I can tell, so most likely there is some inlining going on and the `Option` is in the standard library. Will run the next extraction using debug symbols which may give a more useful stack trace.

**Comment by Chicoryn** [comment]
Probably this stack trace:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  11: <dream_go::nn::network::WorkspaceGuard<'a> as core::ops::deref::DerefMut>::deref_mut
             at src/nn/network.rs:43
  12: dream_go::mcts::predict::PredictState::predict
             at src/mcts/predict.rs:137
  13: dream_go::mcts::predict::PredictState::check
             at src/mcts/predict.rs:186
  14: <dream_go::mcts::predict::PredictState as dream_go::parallel::service::ServiceImpl>::process
             at src/mcts/predict.rs:231
  15: dream_go::parallel::service::worker_thread
             at src/parallel/service.rs:101
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  17: std::panicking::try
             at /checkout/src/libstd/panicking.rs:458
  18: std::panic::catch_unwind
             at /checkout/src/libstd/panic.rs:365
  19: std::thread::Builder::spawn::{{closure}}
             at /checkout/src/libstd/thread/mod.rs:405
  20: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/liballoc/boxed.rs:817
  21: std::sys_common::thread::start_thread
             at /checkout/src/liballoc/boxed.rs:827
             at libstd/sys_common/thread.rs:24
  22: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  23: start_thread
  24: clone
```

**Comment by Chicoryn** [comment]
This might be because we are using an `Rc` and relying on it being unique, which is not necessarily true for the following race condition:

1. Some `WorkspaceGuard` hands the workspace back but has not released its `Rc` yet (because we only hold the lock for the duration of the `drop` function, but the `Rc` lifes for the duration of the struct).
2. Another thread requests a workspace and acquires the `Rc` from step 1.
3. The thread from step 2 tries to use the `Rc` before thread 1 can release it.

This can be fixed by not using an `Rc` to store the workspace. Using, for example, an `Option` instead which we can call `take` on to move the ownership from the guard to the pool in the `drop` function.

**Comment by Chicoryn** [comment]
I re-wrote the `WorkspaceGuard` and `Network` to be less messy. This seems to have fixed this issue.
